# MySQL接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/line_reservation_bot

spring.datasource.username=root

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# データベース設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081