# MySQL接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/line_reservation_bot

spring.datasource.username=root

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# データベース設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# LINE Messaging API
line.channel-access-token=${LINE_CHANNEL_ACCESS_TOKEN}

#=======================================
# メール送信設定
# ========================================

# GmailのSMTPサーバー
spring.mail.host=smtp.gmail.com

# SMTP通信ポート
spring.mail.port=587

# Gmailのアカウント
spring.mail.username=${MAIL_USERNAME}

# Gmailのアプリパスワード
spring.mail.password=${MAIL_PASSWORD}

# SMTP認証を有効にする
spring.mail.properties.mail.smtp.auth=true

# STARTTLSを有効にする
spring.mail.properties.mail.smtp.starttls.enable=true

# 予約通知の送信先
# 後からここを変更するだけで通知先を変更できる
reservation.notification.email=${RESERVATION_NOTIFICATION_EMAIL}
